version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: url-fetcher-mongodb
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: url-fetcher-app
    restart: unless-stopped
    ports:
      - "8080:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      MONGODB_URI: mongodb://mongodb:27017/url-content-fetcher
      CONTENT_SIZE_LIMIT: ${CONTENT_SIZE_LIMIT:-5242880}
      MAX_REDIRECTS: ${MAX_REDIRECTS:-5}
      CONTENT_REFETCH_INTERVAL_HOURS: ${CONTENT_REFETCH_INTERVAL_HOURS:-12}
      REFETCH_CHECK_INTERVAL_MINUTES: ${REFETCH_CHECK_INTERVAL_MINUTES:-30}
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/urls"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local

